### ISSUE TITLE
Issue with installation of tensorrt 9.0.1

### ISSUE THREAD

**Issue by M4R5W0N6** [Limitex/ComfyUI-Diffusers#19]
I'm running into the following issue when running `C:\ComfyUI_windows_portable\python_embeded\python.exe -m streamdiffusion.tools.install-tensorrt`

`Collecting nvidia-cudnn-cu116 (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4)
  Downloading nvidia-cudnn-cu116-0.0.1.dev5.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\marst\AppData\Local\Temp\pip-install-scp8vx03\nvidia-cudnn-cu116_ccc2ef28fddc47bb88a16a018ea4061c\setup.py", line 28, in <module>
          from package_info import __version__
      ModuleNotFoundError: No module named 'package_info'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Error running command: -m pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 54, in <module>
    fire.Fire(install)
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 33, in install
    run_pip(
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\streamdiffusion\pip_utils.py", line 52, in run_pip
    return run_python(f"-m pip {command}", env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\streamdiffusion\pip_utils.py", line 46, in run_python
    raise RuntimeError(f"Error running command: {command}")
RuntimeError: Error running command: -m pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir`

**Comment by Limitex** [comment]
How did you solve this problem?

**Comment by M4R5W0N6** [comment]
had to pip install req's with the embedded pip — also updated inference and diffusers packages in embedded/site-packages
